# Generated by Django 5.0.3 on 2024-03-29 14:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Nurse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='patientEncouter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patientID', models.IntegerField()),
                ('Date', models.DateField(auto_now=True, verbose_name='Date')),
                ('Time', models.TimeField(auto_now=True, verbose_name='Time')),
                ('Encounter', models.CharField(choices=[('Emergency', 'Emergency'), ('OPD', 'OPD'), ('Specialtist Care', 'Specialtist Care')], max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='RegisterPatient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patientID', models.IntegerField(unique=True)),
                ('Surname', models.CharField(max_length=25)),
                ('OtherNames', models.CharField(max_length=100)),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female')], max_length=10)),
                ('PhoneNumber', models.CharField(max_length=20)),
                ('ResidentialAddress', models.CharField(max_length=200)),
                ('EmergencyName', models.CharField(max_length=100)),
                ('EmergencyContact', models.CharField(max_length=20)),
                ('RelationshipwithPatient', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='PatientVitals',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_name', models.CharField(max_length=100)),
                ('blood_pressure', models.CharField(max_length=20)),
                ('temperature', models.DecimalField(decimal_places=2, max_digits=5)),
                ('pulse', models.PositiveSmallIntegerField()),
                ('spO2', models.PositiveSmallIntegerField()),
                ('submission_date', models.DateTimeField(auto_now_add=True)),
                ('nurse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Patient.nurse')),
            ],
        ),
    ]
