# Generated by Django 5.0.3 on 2024-03-31 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Patient', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PatientEncounter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patientID', models.IntegerField()),
                ('Date', models.DateField(auto_now=True, verbose_name='Date')),
                ('Time', models.TimeField(auto_now=True, verbose_name='Time')),
                ('Encounter', models.CharField(choices=[('Emergency', 'Emergency'), ('OPD', 'OPD'), ('Specialtist Care', 'Specialtist Care')], max_length=20)),
                ('Description', models.TextField()),
            ],
        ),
        migrations.DeleteModel(
            name='patientEncouter',
        ),
    ]
